### ISSUE TITLE
Clarify the Data Schema

### ISSUE THREAD

**Issue by makoru-hikage** [makoru-hikage/cynegetica#1]
- Create migration files.
- Supply a proper ERD.

**Comment by eLoyyyyy** [comment]
What tool will you use to draw the ER diagrams ?

**Comment by makoru-hikage** [comment]
MySQL Workbench

**Comment by eLoyyyyy** [comment]
> MySQL Workbench

is it exportable? Can it be displayed here? Because GH has a wiki so we can do documentation pages on those, you know.

**Comment by makoru-hikage** [comment]
Yes, the ERD is exportable.

**Comment by makoru-hikage** [comment]
Doing the first steps

https://github.com/makoru-hikage/cynegetica/commit/5a964ecbb53c3cd6eccf0a4a05d53e6afb3488b9

**Comment by makoru-hikage** [comment]
User *has many* Applications
Application *belongs to one* Job Posts
Job Post *has only one* Job Post Link
Job Post *has only one* Job Post Image
Job Post *belongs to one* Recruiter
Recruiter *belongs to one* Company
Recruiter *has many* Recruiter Links (can lead to GitHub or LinkedIn account)
Recruiter *has many* Recruiter Emails
Recruiter *has many* Mobile Numbers

**Comment by makoru-hikage** [comment]
UPDATE: Recruiter **has only one** email for the meantime and all other datils will be on the "notes" column.
